/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Size } from "./enums/enums";
export namespace Components {
    interface StarRatingComponent {
        /**
          * The size of the stars. Options: small, medium, large Default: medium
         */
        "size": Size;
        /**
          * Number of stars to display. Default: 5
         */
        "stars": number;
    }
}
declare global {
    interface HTMLStarRatingComponentElement extends Components.StarRatingComponent, HTMLStencilElement {
    }
    var HTMLStarRatingComponentElement: {
        prototype: HTMLStarRatingComponentElement;
        new (): HTMLStarRatingComponentElement;
    };
    interface HTMLElementTagNameMap {
        "star-rating-component": HTMLStarRatingComponentElement;
    }
}
declare namespace LocalJSX {
    interface StarRatingComponent {
        /**
          * The size of the stars. Options: small, medium, large Default: medium
         */
        "size"?: Size;
        /**
          * Number of stars to display. Default: 5
         */
        "stars"?: number;
    }
    interface IntrinsicElements {
        "star-rating-component": StarRatingComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "star-rating-component": LocalJSX.StarRatingComponent & JSXBase.HTMLAttributes<HTMLStarRatingComponentElement>;
        }
    }
}
